spring:
    jmx:
        enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:~/librarian;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
          ddl-auto: none
    liquibase:
        change-log: classpath:/liquibase/master.xml
javafx:
    title: Librarian
    stage:
        resizable: false